/* coindex-getopt.h */

/* File autogenerated by gengetopt version 2.20  */

#ifndef COINDEX_GETOPT_H
#define COINDEX_GETOPT_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "coindex"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "0.0.1"
#endif

struct gengetopt_args_info
{
  const char *help_help; /* Print help and exit help description.  */
  const char *version_help; /* Print version and exit help description.  */
  int max_columns_arg;	/* Maximum number of columns to be analyzed. (default='6').  */
  char * max_columns_orig;	/* Maximum number of columns to be analyzed. original value given at command line.  */
  const char *max_columns_help; /* Maximum number of columns to be analyzed. help description.  */
  float threshold_arg;	/* Threshold (default='0.065').  */
  char * threshold_orig;	/* Threshold original value given at command line.  */
  const char *threshold_help; /* Threshold help description.  */
  
  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int max_columns_given ;	/* Whether max-columns was given.  */
  int threshold_given ;	/* Whether threshold was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

extern const char *gengetopt_args_info_purpose;
extern const char *gengetopt_args_info_usage;
extern const char *gengetopt_args_info_help[];

int cmdline_parser (int argc, char * const *argv,
  struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* COINDEX_GETOPT_H */
