/* vigenere-getopt.h */

/* File autogenerated by gengetopt version 2.20  */

#ifndef VIGENERE_GETOPT_H
#define VIGENERE_GETOPT_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "vigenere"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "0.0.1"
#endif

struct gengetopt_args_info
{
  const char *help_help; /* Print help and exit help description.  */
  const char *version_help; /* Print version and exit help description.  */
  char * key_arg;	/* Key to be used for encryption or decryption.  */
  char * key_orig;	/* Key to be used for encryption or decryption original value given at command line.  */
  const char *key_help; /* Key to be used for encryption or decryption help description.  */
  char * out_arg;	/* output file.  */
  char * out_orig;	/* output file original value given at command line.  */
  const char *out_help; /* output file help description.  */
  const char *encrypt_help; /* Encryption help description.  */
  const char *decrypt_help; /* Decryption help description.  */
  
  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int key_given ;	/* Whether key was given.  */
  int out_given ;	/* Whether out was given.  */
  int encrypt_given ;	/* Whether encrypt was given.  */
  int decrypt_given ;	/* Whether decrypt was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
  int opmode_group_counter; /* counter for group opmode */
} ;

extern const char *gengetopt_args_info_purpose;
extern const char *gengetopt_args_info_usage;
extern const char *gengetopt_args_info_help[];

int cmdline_parser (int argc, char * const *argv,
  struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* VIGENERE_GETOPT_H */
