add_test( BbsTest.GetBit [==[/mnt/c/Users/never/Studium/6/Angewandte Kryptographie/repo/AK/src/bin/cryptopp_test]==] [==[--gtest_filter=BbsTest.GetBit]==] --gtest_also_run_disabled_tests)
set_tests_properties( BbsTest.GetBit PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/never/Studium/6/Angewandte Kryptographie/repo/AK/src/Praktikum-CryptoPP/Tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( BbsTest.GetByte [==[/mnt/c/Users/never/Studium/6/Angewandte Kryptographie/repo/AK/src/bin/cryptopp_test]==] [==[--gtest_filter=BbsTest.GetByte]==] --gtest_also_run_disabled_tests)
set_tests_properties( BbsTest.GetByte PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/never/Studium/6/Angewandte Kryptographie/repo/AK/src/Praktikum-CryptoPP/Tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( BbsTest.GetBlock [==[/mnt/c/Users/never/Studium/6/Angewandte Kryptographie/repo/AK/src/bin/cryptopp_test]==] [==[--gtest_filter=BbsTest.GetBlock]==] --gtest_also_run_disabled_tests)
set_tests_properties( BbsTest.GetBlock PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/never/Studium/6/Angewandte Kryptographie/repo/AK/src/Praktikum-CryptoPP/Tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( BbsTest.GetInteger [==[/mnt/c/Users/never/Studium/6/Angewandte Kryptographie/repo/AK/src/bin/cryptopp_test]==] [==[--gtest_filter=BbsTest.GetInteger]==] --gtest_also_run_disabled_tests)
set_tests_properties( BbsTest.GetInteger PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/never/Studium/6/Angewandte Kryptographie/repo/AK/src/Praktikum-CryptoPP/Tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( BbsTest.GetInteger2 [==[/mnt/c/Users/never/Studium/6/Angewandte Kryptographie/repo/AK/src/bin/cryptopp_test]==] [==[--gtest_filter=BbsTest.GetInteger2]==] --gtest_also_run_disabled_tests)
set_tests_properties( BbsTest.GetInteger2 PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/never/Studium/6/Angewandte Kryptographie/repo/AK/src/Praktikum-CryptoPP/Tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( cryptopp_test_TESTS BbsTest.GetBit BbsTest.GetByte BbsTest.GetBlock BbsTest.GetInteger BbsTest.GetInteger2)
